# Generated by Django 3.2.13 on 2022-06-24 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('brnach', models.IntegerField(null=True)),
                ('courses', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='trainee.course')),
            ],
        ),
    ]
